
export enum DeclarationKind {
  SOURCE_FILE = 'sourceFile',
  IMPORT = 'import',
  IMPORT_CLAUSE = 'importClause',
  NAMED_IMPORTS = 'namedImports',
  IMPORT_SPECIFIER = 'importSpecifier',
  NAMESPACED_IMPORT = 'namespacedImport',
  INTERFACE = 'interface',
  CLASS = 'class',
  DECORATOR = 'decorator',
  NAME = 'name',
  TYPE_PARAMETER = 'typeParameter',
  TYPE_REFERENCE = 'typeReference',
  EXPRESSION_WITH_TYPE_ARGUMENTS = 'expressionWithTypeArguments',
  TYPE_ALIAS = 'typeAlias',
  TYPE_LITERAL = 'typeLiteral',
  TYPE_ELEMENT = 'typeElement',
  TYPE_OPERATOR = 'typeOperator',
  CONDITIONAL_TYPE = 'conditionalType',
  HERITAGE = 'heritage',
  CONSTRUCTOR = 'constructor',
  PARAMETER = 'parameter',
  PROPERTY = 'property',
  PROPERTY_SIGNATURE = 'propertySignature',
  METHOD = 'method',
  GETTER = 'getter',
  SETTER = 'setter',
  STRING_LITERAL = 'stringLiteral',
  TUPLE_TYPE = 'tupleType',
  ENUM = 'enum',
  ENUM_MEMBER = 'enumMember',
  VARIABLE = 'variable'
}
